
POST http://localhost:8080/clients HTTP/1.1
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john@j.com"
}

###

POST http://localhost:8080/accounts HTTP/1.1
Content-Type: application/json

{
    "client_id": "28b00925-bf97-48f8-bb3b-9675c4cbd348"
}

###

POST http://localhost:8080/transactions HTTP/1.1
Content-Type: application/json

{
    "account_id_from": "5eed5c64-97de-4744-ab37-7c3854479d55",
    "account_id_to": "3bd44842-dbc9-475b-9be7-934f9961da63",
    "amount": 1
}